{
  "swagger" : "2.0",
  "info" : {
    "description" : "This is the first version of the 3rd Party Integration API specification for Ticketmaster Partners. Through this, the Partners can export their contents to the Ticketmaster ticketing platform in order to sell their inventories through the sales channels enabled.",
    "version" : "0.14.1",
    "title" : "TM 3rd Party Integration API",
    "termsOfService" : "http://tm-3pi-api.ticketmaster.com/terms/",
    "contact" : {
      "email" : "3pi-team@ticketmaster.es"
    },
    "license" : {
      "name" : "Ticketmaster",
      "url" : "http://www.ticketmaster.com/licenses/eib-api_license-1.0.html"
    }
  },
  "host" : "partner.com",
  "basePath" : "/tm-3pi-api/v1",
  "tags" : [ {
    "name" : "event",
    "description" : "A public entertainment pending to take place"
  }, {
    "name" : "manifest",
    "description" : "A seat configuration associated to an event"
  }, {
    "name" : "booking",
    "description" : "An amount of tickets reserved in order to buy them"
  }, {
    "name" : "order",
    "description" : "An amount of tickets purchased"
  } ],
  "schemes" : [ "https" ],
  "paths" : {
    "/healthcheck" : {
      "get" : {
        "summary" : "Health Check Request",
        "description" : "Testing for the reachability of a Partner system and retrieve notifications",
        "operationId" : "HealthCheck",
        "security" : [ {
          "3p_auth" : [ "check:3p-system" ]
        } ]
      }
    },
    "/events" : {
      "get" : {
        "tags" : [ "event" ],
        "summary" : "Retrieves a list of events",
        "description" : "Get an event list from the Partner system",
        "operationId" : "EventListRequest",
        "security" : [ {
          "3p_auth" : [ "ingestion:3p-system" ]
        } ]
      }
    },
    "/events/{event_id}" : {
      "get" : {
        "tags" : [ "event" ],
        "summary" : "Retrieves a specific event.",
        "description" : "Get an event from the Partner system",
        "operationId" : "EventRequest",
        "security" : [ {
          "3p_auth" : [ "ingestion:3p-system" ]
        } ]
      }
    },
    "/events/{event_id}/availability" : {
      "get" : {
        "tags" : [ "event" ],
        "summary" : "Retrieves the availability of an event.",
        "description" : "Get the event availability from the Partner system.",
        "operationId" : "EventAvailabilityRequest",
        "security" : [ {
          "3p_auth" : [ "ingestion:3p-system" ]
        } ]
      }
    },
    "/manifests/{manifest_id}" : {
      "get" : {
        "tags" : [ "manifest" ],
        "summary" : "Retrieves a specific manifest.",
        "description" : "Get a manifest from the Partner system",
        "operationId" : "ManifestRequest",
        "security" : [ {
          "3p_auth" : [ "ingestion:3p-system" ]
        } ]
      }
    },
    "/bookings" : {
      "post" : {
        "tags" : [ "booking" ],
        "summary" : "Inventory Request",
        "description" : "Create a reservation in the Partner ticketing system",
        "operationId" : "InventoryRequest",
        "security" : [ {
          "3p_auth" : [ "runtime:3p-system" ]
        } ]
      }
    },
    "/bookings/{inventory_token}" : {
      "delete" : {
        "tags" : [ "booking" ],
        "summary" : "Inventory Release",
        "description" : "Release a reservation in the Partner system",
        "operationId" : "InventoryRelease",
        "security" : [ {
          "3p_auth" : [ "runtime:3p-system" ]
        } ]
      }
    },
    "/orders" : {
      "get" : {
        "tags" : [ "order" ],
        "summary" : "Retrieves an Order list",
        "description" : "Get an list of order information from the Partner system",
        "operationId" : "OrderResponseList",
        "security" : [ {
          "3p_auth" : [ "runtime:3p-system" ]
        } ]
      },
      "post" : {
        "tags" : [ "order" ],
        "summary" : "Order Request (Inventory Commit)",
        "description" : "Create an order in the Partner ticketing system",
        "operationId" : "OrderRequest",
        "security" : [ {
          "3p_auth" : [ "runtime:3p-system" ]
        } ]
      }
    },
    "/orders/{inventory_order}" : {
      "get" : {
        "tags" : [ "order" ],
        "summary" : "Order Status",
        "description" : "Get the order status from the Partner system",
        "operationId" : "OrderStatus",
        "security" : [ {
          "3p_auth" : [ "runtime:3p-system" ]
        } ]
      },
      "post" : {
        "tags" : [ "order" ],
        "summary" : "Order Print, Order Print Rollback or Order Cancel",
        "description" : "Update an order to print, to rollback the print or to cancel",
        "operationId" : "OrderUpdate",
        "security" : [ {
          "3p_auth" : [ "runtime:3p-system" ]
        } ]
      }
    }
  },
  "securityDefinitions" : {
    "3p_auth" : {
      "type" : "oauth2",
      "tokenUrl" : "http://partner.com/tm-3pi-api/login",
      "flow" : "application",
      "scopes" : {
        "check:3p-system" : "TM can check the Partner system",
        "ingestion:3p-system" : "TM can manage manifests & events from the Partner system",
        "runtime:3p-system" : "TM can manage bookings & orders to the Partner system"
      }
    }
  }
}
